name = "easy_graphics"
description = "Very Simple Graphics Package"
version = "0.1.0"

authors = ["Stephen Merrony"]
maintainers = ["Stephen Merrony <merrony@gmail.com>"]
maintainers-logins = ["SMerrony"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["graphics", "image", "ppm"]

